ENV['VAG_DEFAULT_PROVIDER'] = 'aws'

eval File.read("Vagrantfile.hash_workaround")

Vagrant.configure("2") do |config|

    eval File.read("Vagrantfile.aws")

    config.vm.provision "file", source: ENV['VAG_CREDS'], destination: "/tmp/credentials"
    config.vm.provision "file", source: "kraken.manifest", destination: "/tmp/kraken.manifest"

    config.vm.provision "shell", privileged: true, name: "move credentials", path: "move_creds.bash"

    config.vm.provision "shell", privileged: true, name: "mount EBS storage", env: {"VOLUME_GB" => ENV['VAG_VOLUME_GB']}, path: "mount_ebs.bash"

    config.vm.provision "shell", privileged: true, name: "move manifest", path: "move_manifest.bash"

    config.vm.provision "shell", privileged: true, name: "sync bowtie indexes", path: "sync_from_bt2_bench.bash", args: "bt2-bench/indexes genome-idx/bt"
end
