theme: jekyll-theme-minimal
title: Index zone
description: HTTPS and S3 links to genomic index files freely available in the AWS cloud
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Bowtie
    url: bowtie
  - title: HISAT
    url: hisat
  - title: Kraken/Bracken
    url: k2
  - title: Centrifuge
    url: centrifuge
  - title: SPUMONI
    url: spumoni
