theme: jekyll-theme-minimal
title: Cloud indexes
description: Links to genomic index files available in public clouds
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Bowtie
    url: bowtie
  - title: HISAT
    url: hisat
  - title: Kraken/Bracken
    url: k2
  - title: Centrifuge
    url: centrifuge
