theme: jekyll-theme-minimal
title: Cloud indexes
description: Links to genomic index files available in public clouds
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Tutorial
    url: tutorial
